# Jekyll config

# Site settings
title: Jonathan Whitney
email: jonathan.a.whitney@gmail.com
baseurl: ""
url: "http://jonathanawhitney.com"
github_username:  jawhitney

# Build settings
markdown: kramdown

# Plugins
plugins:
- jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 2 versions
