# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan Whitney
email: jonathan.a.whitney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Jonathan Whitney, Digital Developer
baseurl: "/jw-website"
url: "http://jonathanawhitney.com"
twitter_username: jwhitney64
github_username:  jawhitney

# Build settings
markdown: kramdown
